services:
    crizzo.whoposted.listener:
        class: crizzo\whoposted\event\listener
        arguments:
            - @user
            - @template
            - @dbal.conn
            - %core.root_path%
        tags:
            - { name: event.listener }
